### ISSUE TITLE
Write code for midi playback

### ISSUE THREAD

**Issue by alexfjw** [pyxyyy/gesture-drumkit#18]
Independent of ML side.
Build a basic one first, before adding support for effects.
We can simulate gesture effects by adding 2 sliders on the screen

**Comment by senyuuri** [comment]
Going to implement it in [Oboe](https://github.com/google/oboe) (Android's official high-performance audio library). Code will be written in C++ and exposed to other Java classes through JNI.

- [x] Add C/C++ support to the project
- [x] Integrate Oboe and setup cmake/Gradle 
- [x] Add drum samples and test single track playback
- [x] Add JNI and a demo activity
- [x] Implement mixers (to integrate multiple track into one exclusive `AudioStream`)
- [x] Implement drum machine's timing model (cannot use `Timer` because it can be preempted by the kernel and causes jitter)
- [x] Implement JNIs

**Comment by senyuuri** [comment]
As discussed, below are APIs that will be accessible through JNI.

- set_tempo() 
- play()
- pause()
- update_beat(int track_idx, int velocity)
- reset_track()
- reset_all()
- stop()

**Comment by senyuuri** [comment]
Note: kindly install `NDK` (AndroidStudio > Tools > Android > SDK Manager) if you would like to test this branch.
